// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Template.Services;

#nullable disable

namespace Template.Migrations
{
    [DbContext(typeof(TemplateDbContext))]
    [Migration("20260622103340_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Template.Services.Shared.Appunto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CorsoId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataCaricamento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descrizione")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeFile")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CorsoId");

                    b.HasIndex("UserId");

                    b.ToTable("Appunti");
                });

            modelBuilder.Entity("Template.Services.Shared.Corso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Anno")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Corsi");
                });

            modelBuilder.Entity("Template.Services.Shared.StanzaStudio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CorsoId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsInEsecuzione")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<TimeSpan>("TempoRimanente")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.HasIndex("CorsoId");

                    b.ToTable("StanzeStudio");
                });

            modelBuilder.Entity("Template.Services.Shared.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("NickName")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Template.Services.Shared.Appunto", b =>
                {
                    b.HasOne("Template.Services.Shared.Corso", "Corso")
                        .WithMany()
                        .HasForeignKey("CorsoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Template.Services.Shared.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Corso");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Template.Services.Shared.StanzaStudio", b =>
                {
                    b.HasOne("Template.Services.Shared.Corso", "Corso")
                        .WithMany()
                        .HasForeignKey("CorsoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Corso");
                });
#pragma warning restore 612, 618
        }
    }
}
