// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Template.Services;

#nullable disable

namespace Template.Migrations
{
    [DbContext(typeof(TemplateDbContext))]
    [Migration("20260624141614_AddDataAperturaToStanzaStudio")]
    partial class AddDataAperturaToStanzaStudio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Template.Services.Shared.Appunto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CorsoId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataCaricamento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descrizione")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeFile")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CorsoId");

                    b.HasIndex("UserId");

                    b.ToTable("Appunti");
                });

            modelBuilder.Entity("Template.Services.Shared.CommentoAppunto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AppuntoId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Testo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("AppuntoId");

                    b.HasIndex("UserId");

                    b.ToTable("CommentiAppunti");
                });

            modelBuilder.Entity("Template.Services.Shared.Corso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Anno")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Corsi");
                });

            modelBuilder.Entity("Template.Services.Shared.Esame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CorsoId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CorsoId");

                    b.HasIndex("UserId");

                    b.ToTable("Esami");
                });

            modelBuilder.Entity("Template.Services.Shared.Notifica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ElementoCorrelatoId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("Letta")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Messaggio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifiche");
                });

            modelBuilder.Entity("Template.Services.Shared.SessioneRipasso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descrizione")
                        .HasColumnType("longtext");

                    b.Property<Guid>("EsameId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("EsameId");

                    b.ToTable("SessioniRipasso");
                });

            modelBuilder.Entity("Template.Services.Shared.StanzaStudio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CorsoId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DataApertura")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descrizione")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsInEsecuzione")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<TimeSpan>("TempoRimanente")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.HasIndex("CorsoId");

                    b.ToTable("StanzeStudio");
                });

            modelBuilder.Entity("Template.Services.Shared.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<int>("GiorniDiFila")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("NickName")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<double>("StudioOreDomenica")
                        .HasColumnType("double");

                    b.Property<double>("StudioOreGiovedici")
                        .HasColumnType("double");

                    b.Property<double>("StudioOreLunedici")
                        .HasColumnType("double");

                    b.Property<double>("StudioOreMartedici")
                        .HasColumnType("double");

                    b.Property<double>("StudioOreMercoledici")
                        .HasColumnType("double");

                    b.Property<double>("StudioOreSabato")
                        .HasColumnType("double");

                    b.Property<double>("StudioOreVenerdici")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Template.Services.Shared.Appunto", b =>
                {
                    b.HasOne("Template.Services.Shared.Corso", "Corso")
                        .WithMany()
                        .HasForeignKey("CorsoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Template.Services.Shared.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Corso");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Template.Services.Shared.CommentoAppunto", b =>
                {
                    b.HasOne("Template.Services.Shared.Appunto", "Appunto")
                        .WithMany()
                        .HasForeignKey("AppuntoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Template.Services.Shared.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appunto");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Template.Services.Shared.Esame", b =>
                {
                    b.HasOne("Template.Services.Shared.Corso", "Corso")
                        .WithMany()
                        .HasForeignKey("CorsoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Template.Services.Shared.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Corso");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Template.Services.Shared.Notifica", b =>
                {
                    b.HasOne("Template.Services.Shared.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Template.Services.Shared.SessioneRipasso", b =>
                {
                    b.HasOne("Template.Services.Shared.Esame", "Esame")
                        .WithMany("SessioniRipasso")
                        .HasForeignKey("EsameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Esame");
                });

            modelBuilder.Entity("Template.Services.Shared.StanzaStudio", b =>
                {
                    b.HasOne("Template.Services.Shared.Corso", "Corso")
                        .WithMany()
                        .HasForeignKey("CorsoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Corso");
                });

            modelBuilder.Entity("Template.Services.Shared.Esame", b =>
                {
                    b.Navigation("SessioniRipasso");
                });
#pragma warning restore 612, 618
        }
    }
}
